<?php
return array (
  'capps_address' => 
  array (
    'address_uid' => 'varchar(36) NOT NULL',
    'parent_address_uid' => 'varchar(32)',
    'relation' => 'varchar(255)',
    'status' => 'varchar(32)',
    'type' => 'varchar(16)',
    'customer_number' => 'varchar(64)',
    'company' => 'varchar(128)',
    'company_addition' => 'varchar(128)',
    'street' => 'varchar(128)',
    'street_addition' => 'varchar(128)',
    'postcode' => 'varchar(64)',
    'city' => 'varchar(64)',
    'state' => 'varchar(64)',
    'country' => 'varchar(64)',
    'country_code' => 'varchar(64)',
    'zone' => 'varchar(64)',
    'gender' => 'varchar(16)',
    'title' => 'varchar(64)',
    'firstname' => 'varchar(64)',
    'secondname' => 'varchar(64)',
    'lastname' => 'varchar(64)',
    'nickname' => 'varchar(64)',
    'function' => 'varchar(64)',
    'department' => 'varchar(64)',
    'hobby' => 'varchar(255)',
    'birthday' => 'varchar(32)',
    'email' => 'varchar(64)',
    'url' => 'varchar(255)',
    'phone' => 'varchar(32)',
    'fax' => 'varchar(32)',
    'mobile' => 'varchar(64)',
    'date_created' => 'datetime',
    'date_updated' => 'datetime',
    'active' => 'int(1)',
    'source' => 'varchar(255)',
    'comment' => 'longtext',
    'data' => 'longtext',
    'media' => 'longtext',
    'settings' => 'longtext',
    'addressgroups' => 'varchar(255)',
    'login' => 'varchar(64)',
    'login_alternative' => 'varchar(64)',
    'password' => 'varchar(255)',
    'date_lastlogin' => 'datetime',
    'latitude' => 'double',
    'longitude' => 'double',
    'counter' => 'int(11)',
    'verification_uid' => 'varchar(64)',
    'verification_date' => 'datetime',
    'mcp_token' => 'varchar(64)',
    'mcp_token_created' => 'datetime',
  ),
);
