<?php
return array (
  'capps_medialibrary' => 
  array (
    'medialibrary_uid' => 'varchar(255) NOT NULL',
    'type' => 'varchar(255)',
    'address_uid' => 'varchar(36)',
    'context' => 'varchar(255)',
    'relation' => 'varchar(255)',
    'addressgroups' => 'varchar(255)',
    'categories' => 'varchar(255)',
    'title' => 'varchar(255)',
    'file' => 'varchar(255)',
    'section' => 'varchar(32)',
    'path' => 'varchar(255)',
    'name' => 'varchar(255)',
    'extension' => 'varchar(255)',
    'mime_type' => 'varchar(255)',
    'description' => 'mediumtext',
    'keywords' => 'mediumtext',
    'copyright' => 'varchar(255)',
    'author' => 'varchar(255)',
    'source' => 'varchar(32)',
    'device' => 'varchar(255)',
    'date_created' => 'datetime',
    'date_updated' => 'datetime',
    'date_start' => 'datetime',
    'date_end' => 'datetime',
    'date_deleted' => 'datetime',
    'active' => 'int(1)',
    'deleted' => 'int(1)',
    'data' => 'mediumtext',
    'media' => 'mediumtext',
    'tags' => 'varchar(255)',
    'flags' => 'varchar(255)',
  ),
);
